### ISSUE TITLE
登陆验证

### ISSUE THREAD

**Issue by fanyebo** [toddlerya/NebulaSolarDash#5]
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[05/09/17 15:28:02] : ERROR   : can not logon 127.0.0.1 without passwd.

这个密码应该在哪里设置，或是在哪块代码中配置

**Comment by toddlerya** [comment]
需要先做好从服务端到客户端的主机信任，即可以从服务端直接ssh连接到客户端，你百度下，有想着教程的。

**Comment by toddlerya** [comment]
客户端服务端都在本机，也要做好信任，就是直接ssh 127.0.0.1免密码输入可以登陆即可。

**Comment by toddlerya** [comment]
不是问题~
