### ISSUE TITLE
启动在json update的时候会报错，不知道你是怎么处理，可以提交代码吗，会维护吗，你的ip获取那块是有点问题的

### ISSUE THREAD

**Issue by b1gw00d** [toddlerya/NebulaSolarDash#8]
启动在json update的时候会报错，不知道你是怎么处理，可以提交代码吗，会维护吗，你的ip获取那块是有点问题的

**Comment by 601040605** [comment]
启动在json update的时候会报错，不知道你是怎么处理，可以提交代码吗，会维护吗，你的ip获取那块是有点问题的

**Comment by toddlerya** [comment]
获取IP是通过Python的socket 模块实现的，依赖于hosts 里填写的主机名，因为我的服务器都是我用工具统一部署初始化的，所以没遇到这个问题。欢迎提交代码，我会维护这个项目的🤝

**Comment by b1gw00d** [comment]
断网环境测试是返还127.0.0.1

**Comment by toddlerya** [comment]
举个例子😬：
假设你的服务器主机名是`haha`，
你的`/etc/hosts`里面内容为
```
127.0.0.1  localhost
192.168.1.102  haha
```
那么程序就可以通过socket模块根据主机名`haha`获取到你的IP地址192.168.1.102。

这么处理是有缺陷的，但是满足我的个人需求了，所以就没有再进行优化处理，如果你有好想法可以提交代码来优化下呢😃。

**Comment by b1gw00d** [comment]
def local_ip():
        try:
        csock =socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
        csock.connect(('8.8.8.8',80))
        (addr,port)=csock.getsockname()
        csock.close()
        return addr
    except socket.error:
        return "127.0.0.1"
你测试一下

**Comment by b1gw00d** [comment]
gethostbyname的方法在很多机器是有一定为题的，很容易获取到回环地址，加个好友沟通下？

**Comment by toddlerya** [comment]
toddlerya@qq.com，邮件联系我吧

**Comment by toddlerya** [comment]
@b1gw00d 试了下，你的方法真的好用，我修改下代码~谢谢你的建议。最近一直在出差，刚刚回到家。

**Comment by toddlerya** [comment]
@b1gw00d 已经合入你的代码~谢谢啦
